package form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */import java.util.Arrays;
import java.util.Collections;


/**
 *
 * @author jz808
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        courses = new javax.swing.JLabel();
        course1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        course6 = new javax.swing.JTextField();
        course7 = new javax.swing.JTextField();
        course8 = new javax.swing.JTextField();
        course2 = new javax.swing.JTextField();
        course3 = new javax.swing.JTextField();
        course4 = new javax.swing.JTextField();
        course5 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        currentGrade = new javax.swing.JLabel();
        currentGrade2 = new javax.swing.JTextField();
        currentGrade3 = new javax.swing.JTextField();
        currentGrade8 = new javax.swing.JTextField();
        currentGrade1 = new javax.swing.JTextField();
        currentGrade5 = new javax.swing.JTextField();
        currentGrade6 = new javax.swing.JTextField();
        currentGrade7 = new javax.swing.JTextField();
        currentGrade4 = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        goal2 = new javax.swing.JTextField();
        goal1 = new javax.swing.JTextField();
        goal7 = new javax.swing.JTextField();
        goal6 = new javax.swing.JTextField();
        goal8 = new javax.swing.JTextField();
        goal5 = new javax.swing.JTextField();
        goal3 = new javax.swing.JTextField();
        goal4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resource = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courses.setText("Courses:");

        course1.setMinimumSize(new java.awt.Dimension(20, 50));
        course1.setPreferredSize(new java.awt.Dimension(100, 50));
        course1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Study Plan");

        course6.setMinimumSize(new java.awt.Dimension(20, 50));
        course6.setPreferredSize(new java.awt.Dimension(100, 50));
        course6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course6ActionPerformed(evt);
            }
        });

        course7.setMinimumSize(new java.awt.Dimension(20, 50));
        course7.setPreferredSize(new java.awt.Dimension(100, 50));
        course7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course7ActionPerformed(evt);
            }
        });

        course8.setMinimumSize(new java.awt.Dimension(20, 50));
        course8.setPreferredSize(new java.awt.Dimension(100, 50));
        course8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course8ActionPerformed(evt);
            }
        });

        course2.setMinimumSize(new java.awt.Dimension(20, 50));
        course2.setPreferredSize(new java.awt.Dimension(100, 50));
        course2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course2ActionPerformed(evt);
            }
        });

        course3.setMinimumSize(new java.awt.Dimension(20, 50));
        course3.setPreferredSize(new java.awt.Dimension(100, 50));
        course3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course3ActionPerformed(evt);
            }
        });

        course4.setMinimumSize(new java.awt.Dimension(20, 50));
        course4.setPreferredSize(new java.awt.Dimension(100, 50));
        course4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course4ActionPerformed(evt);
            }
        });

        course5.setMinimumSize(new java.awt.Dimension(20, 50));
        course5.setPreferredSize(new java.awt.Dimension(100, 50));
        course5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course5ActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        currentGrade.setText("Current Grade:");

        currentGrade2.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade2.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade2ActionPerformed(evt);
            }
        });

        currentGrade3.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade3.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade3ActionPerformed(evt);
            }
        });

        currentGrade8.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade8.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade8ActionPerformed(evt);
            }
        });

        currentGrade1.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade1.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade1ActionPerformed(evt);
            }
        });

        currentGrade5.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade5.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade5ActionPerformed(evt);
            }
        });

        currentGrade6.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade6.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade6ActionPerformed(evt);
            }
        });

        currentGrade7.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade7.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade7ActionPerformed(evt);
            }
        });

        currentGrade4.setMinimumSize(new java.awt.Dimension(20, 50));
        currentGrade4.setPreferredSize(new java.awt.Dimension(100, 50));
        currentGrade4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentGrade4ActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Areas of Improvement:");

        jLabel3.setText("Grade Goal:");

        goal2.setMinimumSize(new java.awt.Dimension(20, 50));
        goal2.setPreferredSize(new java.awt.Dimension(100, 50));
        goal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal2ActionPerformed(evt);
            }
        });

        goal1.setMinimumSize(new java.awt.Dimension(20, 50));
        goal1.setPreferredSize(new java.awt.Dimension(100, 50));
        goal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal1ActionPerformed(evt);
            }
        });

        goal7.setMinimumSize(new java.awt.Dimension(20, 50));
        goal7.setPreferredSize(new java.awt.Dimension(100, 50));
        goal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal7ActionPerformed(evt);
            }
        });

        goal6.setMinimumSize(new java.awt.Dimension(20, 50));
        goal6.setPreferredSize(new java.awt.Dimension(100, 50));
        goal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal6ActionPerformed(evt);
            }
        });

        goal8.setMinimumSize(new java.awt.Dimension(20, 50));
        goal8.setPreferredSize(new java.awt.Dimension(100, 50));
        goal8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal8ActionPerformed(evt);
            }
        });

        goal5.setMinimumSize(new java.awt.Dimension(20, 50));
        goal5.setPreferredSize(new java.awt.Dimension(100, 50));
        goal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal5ActionPerformed(evt);
            }
        });

        goal3.setMinimumSize(new java.awt.Dimension(20, 50));
        goal3.setPreferredSize(new java.awt.Dimension(100, 50));
        goal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal3ActionPerformed(evt);
            }
        });

        goal4.setMinimumSize(new java.awt.Dimension(20, 50));
        goal4.setPreferredSize(new java.awt.Dimension(100, 50));
        goal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Fill in every box. For empty boxes, enter a 0");

        jLabel6.setText("Resources to help you improve:");

        resource.setMinimumSize(new java.awt.Dimension(20, 50));
        resource.setPreferredSize(new java.awt.Dimension(100, 50));
        resource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(courses)
                                    .addComponent(course1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(currentGrade7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentGrade6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentGrade5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentGrade3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentGrade2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentGrade)
                                    .addComponent(currentGrade1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentGrade4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currentGrade8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(goal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resource, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 274, Short.MAX_VALUE))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courses)
                            .addComponent(currentGrade)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(resource, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(course2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(currentGrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(goal2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentGrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentGrade4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentGrade5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentGrade6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentGrade7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goal7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goal8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentGrade8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(submit))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(exit))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourceActionPerformed

    private void goal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal4ActionPerformed

    private void goal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal3ActionPerformed

    private void goal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal5ActionPerformed

    private void goal8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal8ActionPerformed

    private void goal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal6ActionPerformed

    private void goal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal7ActionPerformed

    private void goal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal1ActionPerformed

    private void goal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal2ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        course1.setText("");
        course2.setText("");
        course3.setText("");
        course4.setText("");
        course5.setText("");
        course6.setText("");
        course7.setText("");
        course8.setText("");
        currentGrade1.setText("");
        currentGrade2.setText("");
        currentGrade3.setText("");
        currentGrade4.setText("");
        currentGrade5.setText("");
        currentGrade6.setText("");
        currentGrade7.setText("");
        currentGrade8.setText("");
        goal1.setText("");
        goal2.setText("");
        goal3.setText("");
        goal4.setText("");
        goal5.setText("");
        goal6.setText("");
        goal7.setText("");
        goal8.setText("");
        resource.setText("");
        jLabel4.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void currentGrade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade4ActionPerformed

    private void currentGrade7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade7ActionPerformed

    private void currentGrade6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade6ActionPerformed

    private void currentGrade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade5ActionPerformed

    private void currentGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade1ActionPerformed

    private void currentGrade8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade8ActionPerformed

    private void currentGrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade3ActionPerformed

    private void currentGrade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentGrade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentGrade2ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        float markCourse1, markCourse2, markCourse3, markCourse4, markCourse5, markCourse6, markCourse7, markCourse8;
        float markGoal1, markGoal2, markGoal3, markGoal4, markGoal5, markGoal6, markGoal7, markGoal8;
        try {
            jLabel5.setText("Fill in every box. For empty boxes, fill in a 0 for the mark");
            
            //Retrieves marks from the text fields
            markCourse1 = Float.parseFloat(currentGrade1.getText());
            markCourse2 = Float.parseFloat(currentGrade2.getText());
            markCourse3 = Float.parseFloat(currentGrade3.getText());
            markCourse4 = Float.parseFloat(currentGrade4.getText());
            markCourse5 = Float.parseFloat(currentGrade5.getText());
            markCourse6 = Float.parseFloat(currentGrade6.getText());
            markCourse7 = Float.parseFloat(currentGrade7.getText());
            markCourse8 = Float.parseFloat(currentGrade8.getText());

            markGoal1 = Float.parseFloat(goal1.getText());
            markGoal2 = Float.parseFloat(goal2.getText());
            markGoal3 = Float.parseFloat(goal3.getText());
            markGoal4 = Float.parseFloat(goal4.getText());
            markGoal5 = Float.parseFloat(goal5.getText());
            markGoal6 = Float.parseFloat(goal6.getText());
            markGoal7 = Float.parseFloat(goal7.getText());
            markGoal8 = Float.parseFloat(goal8.getText());

            //checks if the numbers entered are valid
            if ((markCourse1 <= markGoal1) && (markCourse2 <= markGoal2) && (markCourse3 <= markGoal3) && (markCourse4 <= markGoal4) && (markCourse5 <= markGoal5) && (markCourse6 <= markGoal6) && (markCourse7 <= markGoal7) && (markCourse8 <= markGoal8)) {
             //calculatees mark differences
                float markDiff1 = markCourse1 - markGoal1;
                float markDiff2 = markCourse2 - markGoal2;
                float markDiff3 = markCourse3 - markGoal3;
                float markDiff4 = markCourse4 - markGoal4;
                float markDiff5 = markCourse5 - markGoal5;
                float markDiff6 = markCourse6 - markGoal6;
                float markDiff7 = markCourse7 - markGoal7;
                float markDiff8 = markCourse8 - markGoal8;

                //creates an array of these differences and sorts them to find the worst mark
    float[] arrayOfDiffs = new float[] { markDiff1, markDiff2, markDiff3, markDiff4, markDiff5, markDiff6,
        markDiff7, markDiff8 };
        Arrays.sort(arrayOfDiffs);
        float worstDiff = arrayOfDiffs[0];
        
        //array of links and subjects
        String[] links = new String[] { "https://www.khanacademy.org/math/get-ready-for-algebra-i",
                        "https://www.khanacademy.org/math/algebra", "https://www.khanacademy.org/math/geometry",
                        "https://www.khanacademy.org/math/algebra2", "https://www.khanacademy.org/math/precalculus",
                        "https://www.khanacademy.org/math/ap-calculus-ab",
                        "https://www.khanacademy.org/math/ap-calculus-bc",
                        "https://www.khanacademy.org/math/ap-statistics",
                        "https://www.khanacademy.org/math/multivariable-calculus",
                        "https://www.khanacademy.org/science/high-school-biology",
                        "https://www.khanacademy.org/science/ap-biology",
                        "https://www.khanacademy.org/science/organic-chemistry",
                        "https://www.khanacademy.org/science/ap-chemistry-beta",
                        "https://www.khanacademy.org/science/high-school-physics",
                        "https://www.khanacademy.org/science/ap-college-physics-1",
                        "https://www.khanacademy.org/science/ap-physics-2",
                        "https://www.albert.io/ap-physics-c-e-and-m",
                        "https://www.khanacademy.org/science/ap-college-environmental-science",
                        "https://www.khanacademy.org/science/cosmology-and-astronomy",
                        "https://www.albert.io/health", "https://www.khanacademy.org/ela/cc-9th-reading-vocab",
                        "https://www.albert.io/ap-english-language/overview",
                        "https://www.albert.io/blog/ap-english-literature/",
                        "https://youtube.com/playlist?list=PLoGgviqq4847gGLvmfXPT5pYZRqBqsqLN",
                        "https://youtube.com/playlist?list=PLEHRHjICEfDVLBpD1Rkc04M8G5Pn4bSVH",
                        "https://www.khanacademy.org/humanities/world-history",
                        "https://youtube.com/playlist?list=PLEHRHjICEfDWDNjJgvnNTHfUFv3Sgjgb6",
                        "https://www.khanacademy.org/humanities/art-history",
                        "https://www.khanacademy.org/humanities/us-history",
                        "https://www.khanacademy.org/humanities/ap-us-history",
                        "https://www.khanacademy.org/humanities/ap-us-government-and-politics",
                        "https://www.khanacademy.org/economics-finance-domain/ap-macroeconomics",
                        "https://www.khanacademy.org/economics-finance-domain/ap-microeconomics",
                        "https://www.albert.io/ap-comparative-government",
                        "https://youtube.com/playlist?list=PLoGgviqq4847R2JKQ7-nYVhrnD2ajSG7Y",
                        "https://www.duolingo.com/course/zh/en/Learn-Chinese",
                        "https://youtube.com/playlist?list=PLoGgviqq48450RQdBgdqj-a4J0eD9lrkw",
                        "https://www.thefrenchexperiment.com",
                        "https://youtube.com/playlist?list=PLoGgviqq4847NrGXhnmp6QnzSwknYH3SJ",
                        "https://www.albert.io/spanish-1",
                        "https://youtube.com/playlist?list=PLoGgviqq4844xCVbFUawcSsJ_iOJ_3Cvt",
                        "https://youtube.com/playlist?list=PLoGgviqq4844fvUz7G3obGEDqiz5q8G9L",
                        "https://youtube.com/playlist?list=PLoGgviqq4847sWgSD6H0I18jdFzxNrvGj",
                        "https://youtube.com/playlist?list=PLoGgviqq48459FanuiZNHWzyvs8AfIEre",
                        "https://youtube.com/playlist?list=PL2rZQvyPycXJPaPuFSvtlyQxmb6GfNUP_",
                        "https://www.khanacademy.org/computing/ap-computer-science-principles",
                        "https://www.albert.io/ap-computer-science-a",
                        "https://www.khanacademy.org/computing/computer-science",
                        "https://www.albert.io/ap-music-theory",
                        "https://www.khanacademy.org/science/electrical-engineering"
                };
                String[] subjects = new String[] { "Pre-Algebra", "Algebra 1", "Geometry", "Algebra 2", "Pre-Calculus",
                        "Calculus AB", "Calculus BC", "AP Statistics", "Multivariable Calculus",
                        "Biology", "AP Biology", "Chemistry", "AP Chemistry", "Physics", "AP Physics 1", "AP Physics 2",
                        "AP Physics C", "AP Environmental", "Earth & Space/Astronomy", "Health",
                        "English", "AP English Language & Composition", "AP English Literature & Composition",
                        "AP Human Geography", "World History", "AP World History", "AP European History",
                        "AP Art History", "US History", "US History", "AP US History", "AP US Government & Poltiics",
                        "AP Macroeconomics", "AP Microeconomics", "AP Comparative Government", "AP Chinese", "Chinese",
                        "AP French", "AP Spanish", "Spanish", "AP German", "AP Italian", "AP Japanese",
                        "AP Latin", "American Sign Language", "AP Computer Science Principles", "AP Computer Science A",
                        "Computer Science", "AP Music Theory", "Engineeriing Science" };

        String lowestMark = String.valueOf(worstDiff);
        
        //compares mark difference to the subject
        if (markDiff1 == worstDiff) {
            lowestMark = course1.getText();
        } else if (markDiff2 == worstDiff) {
            lowestMark = course2.getText();
        } else if (markDiff3 == worstDiff) {
            lowestMark = course3.getText();
        } else if (markDiff4 == worstDiff) {
            lowestMark = course4.getText();
        } else if (markDiff5 == worstDiff) {
            lowestMark = course5.getText();
        } else if (markDiff6 == worstDiff) {
            lowestMark = course6.getText();
        } else if (markDiff7 == worstDiff) {
            lowestMark = course7.getText();
        } else {
            lowestMark = course8.getText();
        }
        
        //prints out their worst subject and a resource for them
        jLabel4.setText(lowestMark + " is your lowest mark.");
        int num =0;
        for(int i = 0;i<50;i++){
            if(lowestMark.equalsIgnoreCase(subjects[i])){
                resource.setText(links[i]);
                num++;
            }
        }
 if(num==0){ //if the subject is not in the array
     resource.setText("No Data Found.");
 }

        } else { //if the user does not enter valid numbers
            jLabel5.setText("Please only enter valid numbers");
        }
        } catch (NumberFormatException e) {
            jLabel5.setText("Please only enter valid numbers");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void course5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course5ActionPerformed

    private void course4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course4ActionPerformed

    private void course3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course3ActionPerformed

    private void course2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course2ActionPerformed

    private void course8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course8ActionPerformed

    private void course7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course7ActionPerformed

    private void course6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course6ActionPerformed

    private void course1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTextField course1;
    private javax.swing.JTextField course2;
    private javax.swing.JTextField course3;
    private javax.swing.JTextField course4;
    private javax.swing.JTextField course5;
    private javax.swing.JTextField course6;
    private javax.swing.JTextField course7;
    private javax.swing.JTextField course8;
    private javax.swing.JLabel courses;
    private javax.swing.JLabel currentGrade;
    private javax.swing.JTextField currentGrade1;
    private javax.swing.JTextField currentGrade2;
    private javax.swing.JTextField currentGrade3;
    private javax.swing.JTextField currentGrade4;
    private javax.swing.JTextField currentGrade5;
    private javax.swing.JTextField currentGrade6;
    private javax.swing.JTextField currentGrade7;
    private javax.swing.JTextField currentGrade8;
    private javax.swing.JButton exit;
    private javax.swing.JTextField goal1;
    private javax.swing.JTextField goal2;
    private javax.swing.JTextField goal3;
    private javax.swing.JTextField goal4;
    private javax.swing.JTextField goal5;
    private javax.swing.JTextField goal6;
    private javax.swing.JTextField goal7;
    private javax.swing.JTextField goal8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resource;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
